[package]
name = "moviehub"
version = "1.0.0"
description = "MovieHub Entertainment Portal"
author = "MovieHub Team"
license = "MIT"
repository = ""

[dependencies]
"php/php" = "=8.3"

[fs]
"/app/" = "."

[[command]]
name = "run"
module = "php/php:php"
runner = "wasi"

[command.annotations.wasi]
main-args = ["-t", "/app/public", "-S", "0.0.0.0:8000"]

[deployment]
runtime = "php"
version = "8.3"
